### ISSUE TITLE
wont import sample files

### ISSUE THREAD

**Issue by MHDES** [eliemichel/MapsModelsImporter-samples#5]
Hello 
I have tried v3.5 which didnt work, I also tried switching on the Debug and couldnt find anything on my system named "toggle System Console".
So then I tried v3.4, same initial error immediately pops up and again even after turning on debug nothing seems to happen.

I have tried this importing a file I created with RenderDoc, and with sample file Funkhaus and bridge-RD as well

I am using Blender 2.9, but I also tried it on an older verion I have 2.8 and that didnt work either?!
Any help much appreciated
Regards

**Comment by MHDES** [comment]
oh - this is the error:
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this AddOn
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version >= 1.10 for MapsModelsImporter >= 0.3.3
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading. 
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output

**Comment by eliemichel** [comment]
Use a capture made with RenderDoc v1.10, the last version of this add-on (v0.3.5) and the last version of Blender (2.91). Even though other combinations can work this is the recommended. Once you've made sure you're using these versions, please also report which rdc file you were trying to import exactly and any error message occurring before what you've reported here!
The system console is accessible through the "Window" menu of Blender on Windows.

**Comment by MHDES** [comment]
In between the OP and the reply above i tried different combos
and found by  using 3.4 and 2.91 blender and I managed to import renderdoc 1.6 captures, sometimes.
my question is, if i switch to 3.5 and v1.10 will it be an improvement?
and can i  have 3.4  **and** 3.5 as addon for blender? or will i have to get rid of 3.4, (im worried to get rid of something that works, even if sporadically).
similarly do u know if i can have both renderdoc 1.6 and v1.10 on my machine?

thanks

**Comment by eliemichel** [comment]
You can have different versions of RenderDoc at the same time (especially if getting the Portable versions on the download page), but you cannot have multiple versions of the same add-on installed. A hack can be to change the name of the addon in `__init__.py` (unzip, edit, rezip) so that Blender thinks it is two different addons. Or you can simply keep the zips somewhere and uninstall/reinstall the correct version of the addon when you need so.

There is no drastic feature gain in switching to 3.5 + RD1.10 but it is recommended to use latest versions as I am not going to fix potential issues on older ones.

**Comment by hu277** [comment]
I tried to import the sample bridge with the recommended versions (Blender2.91, RenderDoc 1.10, mapsmodelsimporter 3.5) but getting the following error:

==========================================================================================
google_maps_rd failed and returned:
Loading capture from F:\Customscenery\Bilder\bridge-RD_1.10.rdc...
Couldn't open file: ReplayStatus.FileCorrupted
Traceback (most recent call last):
  File "C:\Users\Uwe\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 290, in <module>
    main(controller)
  File "C:\Users\Uwe\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 282, in main
    scraper.run()
  File "C:\Users\Uwe\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 207, in run
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

Other samples like the Funkturm or the Alhambra model results in the same error.
Regards

**Comment by nimitz2000** [comment]
Also trying quite times to import sample rdc's files with reccomended Blender / importmaps version and allways errors like:
Python: Traceback (most recent call last):
  File "C:\Users\administrador\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\administrador\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\google_maps.py", line 306, in importCapture
    captureToFiles(context, filepath, prefix, max_blocks)
  File "C:\Users\administrador\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\google_maps.py", line 78, in captureToFiles
    out = subprocess.check_output([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)], stderr=subprocess.STDOUT)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] El parámetro no es correcto

location: <unknown location>:-1

**Comment by eliemichel** [comment]
@nimitz2000 try to install Visual C++ redistributable: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by nimitz2000** [comment]
tried to install Redistributables 2015-2019 but no luck...

In the meanwhile installed into another computer with same program 
versions and it worked...

will try some things, any idea from your side?

Un cordial saludo

Un cordial saludo.

________*
*Antoni Coll*
*mob: 607 344 377

N19interactiva
Servicios 3d&Infografía avanzados
Major 88, (07530) Sant Llorenç des Cardassar, Mallorca.
Tel. 971 838 655Fax 971 838 655
*www.n19interactiva.com <http://www.n19interactiva.com/>*
<http://www.n19interactiva.com/>PPlease don't print this e-mail unless 
you really need to.

*"*AVISO DE CONFIDENCIALIDAD: Este mensaje y sus documentos adjuntos, 
pueden contener información privilegiada y/o confidencial que está 
dirigida exclusivamente a su destinatario. Si usted recibe este mensaje 
y no es el destinatario indicado, o el empleado encargado de su entrega 
a dicha persona, por favor, notifíquelo inmediatamente y remita el 
mensaje original a la dirección de correo electrónico indicada. 
Cualquier copia, uso o distribución no autorizados de esta comunicación 
queda estrictamente prohibida. *

**CONFIDENTIALITY NOTICE: This e-mail and the accompanying document(s) 
contain confidential information which is privileged and intended only 
for the addressee here of. If you are not the intended recipient, you 
are here by notified that any disclosure, copying, distribution or use 
of this e-mail and/or accompanying document(s) is strictly prohibited. 
If you have received this e-mail in error, please immediately notify the 
sender at the above e-mail address.*"

**Comment by eliemichel** [comment]
Maybe just restarting after the installation, then I don't know, the problem does not occur in my code, it occurs in Python's subprocess module, in the way it creates a new process.
