### ISSUE TITLE
import fail

### ISSUE THREAD

**Issue by obesoleso** [eliemichel/MapsModelsImporter-samples#8]
Hello!

My name's Guido I work with GIS and im super excited to try this tool for Blender.

I cant import my captures and after a few tries I downloaded the samples.
I cant import them neither.
I downloaded Blender 2.82 (but i had same issue with 2.83 and 2.92)
I downloaded these samples: "HongKong.rdc" and "Funkhaus.rdc"
Maps Models Importer is 0.36

Here's the log:

google_maps_rd failed and returned:
Loading capture from C:\Users\username\Desktop\HongKong.rdc...
Trying scraping strategy #4...
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 1.000000)
(Skipping drawcall ClearDepthStencilView(D=1.000000, S=00))
(Skipping drawcall Draw(4))
(Skipping drawcall Draw(4))
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 1.000000)
Not relevant yet: ClearDepthStencilView(D=1.000000, S=00)
Not relevant yet: DrawIndexed(3937)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: ClearDepthStencilView(S=00)
Not relevant yet: DrawIndexed(478)
Not relevant yet: ClearDepthStencilView(D=1.000000, S=00)
Not relevant yet: Draw(24)
Not relevant yet: Draw(30)
Not relevant yet: Draw(48)
Not relevant yet: Draw(18)
Not relevant yet: Draw(12)
Not relevant yet: Draw(90)
Not relevant yet: Draw(120)
Not relevant yet: Draw(42)
Not relevant yet: Draw(12)
Not relevant yet: Draw(156)
Not relevant yet: Draw(120)
Not relevant yet: Draw(54)
Not relevant yet: Draw(102)
Not relevant yet: Draw(102)
Not relevant yet: Draw(126)
Not relevant yet: Draw(102)
Not relevant yet: Draw(138)
Not relevant yet: Draw(126)
Not relevant yet: Draw(138)
Not relevant yet: Draw(156)
Not relevant yet: Draw(96)
Not relevant yet: Draw(150)
Not relevant yet: Draw(96)
Not relevant yet: Draw(30)
Not relevant yet: Draw(78)
Not relevant yet: Draw(60)
Not relevant yet: Draw(24)
Not relevant yet: Draw(42)
Not relevant yet: Draw(72)
Not relevant yet: Draw(48)
Not relevant yet: Draw(72)
Not relevant yet: Draw(6)
Not relevant yet: Draw(108)
Not relevant yet: Draw(12)
Not relevant yet: Draw(12)
Not relevant yet: Draw(12)
Not relevant yet: Draw(12)
Not relevant yet: Draw(12)
Not relevant yet: Draw(24)
Not relevant yet: Draw(30)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(30)
Not relevant yet: Draw(36)
Not relevant yet: Draw(24)
Not relevant yet: Draw(18)
Not relevant yet: Draw(18)
Not relevant yet: Draw(18)
Not relevant yet: Draw(18)
Not relevant yet: Draw(84)
Not relevant yet: Draw(12)
Not relevant yet: Draw(30)
Not relevant yet: Draw(48)
Not relevant yet: Draw(12)
Not relevant yet: Draw(30)
Not relevant yet: Draw(24)
Not relevant yet: Draw(12)
Not relevant yet: Draw(12)
Not relevant yet: Draw(36)
Not relevant yet: Draw(18)
Not relevant yet: Draw(54)
Not relevant yet: Draw(6)
Not relevant yet: Draw(36)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Present(ResourceId::123)
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 299, in <module>
    main(controller)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 291, in main
    scraper.run()
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 217, in run
    relevant_drawcalls, capture_type = self.extractRelevantCalls(drawcalls)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 198, in extractRelevantCalls
    return self.extractRelevantCalls(drawcalls, _strategy=_strategy+1)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 166, in extractRelevantCalls
    if self.hasUniform(skipped_drawcalls[0], "_uMeshToWorldMatrix"):
IndexError: list index out of range

Thank you!

**Comment by obesoleso** [comment]
I forgot one detail: I already have Python 2.7 and 3.6 installed on my system.

**Comment by obesoleso** [comment]
update!

It works!

Im using these:

Chrome 89.0.4389.90
Blender 2.92
MapModelsImporter 0.3.4
Renderdoc 1.1.0

cheers!
